version: '3.8'
services:
  backend:
    build: ./app/backend
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 3s
      retries: 3

  frontend:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app/frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
